export const featuresCity = {
    brazil: {
        texture: './location/brazil.png',
        dollyPosX: 20,
        dollyPosY: -0.3,
        dollyPosZ: -3,
        sizeX: 5,
        sizeY: 4,
        sizeZ: 0.0001,
    },
    germany: {
        texture: './location/germany.png',
        dollyPosX: 39.95,
        dollyPosY: -0.9,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.9,
        sizeZ: 0.0001,
    },
    paris: {
        texture: './location/paris.png',
        dollyPosX: 59.95,
        dollyPosY: -0.6,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 3.5,
        sizeZ: 0.0001,
    },
    aus: {
        texture: './location/aus.png',
        dollyPosX: 79.95,
        dollyPosY: -1.5,
        dollyPosZ: -3,
        sizeX: 4,
        sizeY: 1.8,
        sizeZ: 0.0001,
    },
    canada: {
        texture: './location/canada.png',
        dollyPosX: 99.95,
        dollyPosY: -0.6,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 3.5,
        sizeZ: 0.0001,
    },
    china: {
        texture: './location/china.png',
        dollyPosX: 119.95,
        dollyPosY: -0.6,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 3.5,
        sizeZ: 0.0001,
    },
    cr: {
        texture: './location/cr.png',
        dollyPosX: 139.95,
        dollyPosY: -0.6,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 3.5,
        sizeZ: 0.0001,
    },
    egypt: {
        texture: './location/egypt.png',
        dollyPosX: 159.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    greece: {
        texture: './location/greece.png',
        dollyPosX: 179.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    ind: {
        texture: './location/ind.png',
        dollyPosX: 199.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    lon: {
        texture: './location/lon.png',
        dollyPosX: 219.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    mynamar: {
        texture: './location/mynamar.png',
        dollyPosX: 239.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    rus: {
        texture: './location/rus.png',
        dollyPosX: 259.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    },
    spain: {
        texture: './location/spain.png',
        dollyPosX: 279.95,
        dollyPosY: -1.15,
        dollyPosZ: -3,
        sizeX: 4.8,
        sizeY: 2.5,
        sizeZ: 0.0001,
    }
};